version: "3.3"

services:
  users-api:
    depends_on:
      - database
    restart: always
    build:
      context: .
    networks:
      - network-database
    ports:
      - 8080:8080
      - 8081:8081
      - 50051:50051
    env_file: .env.docker
   
  database:
    image: scylladb/scylla:6.1
    restart: always
    ports:
    - 9042:9042
    expose:
      - 9042
    volumes:
      - db-data:/var/lib/scylla
      - ./scylla/cassandra-rackdc.properties:/etc/scylla/cassandra-rackdc.properties
    container_name: database
    command: --seeds=database,database2,database3
    networks:
      - network-database

  database2:
    depends_on:
      - database
    image: scylladb/scylla:6.1
    restart: always
    ports:
    - 9043:9042
    expose:
      - 9042
    volumes:
      - db-data2:/var/lib/scylla
      - ./scylla/cassandra-rackdc.properties:/etc/scylla/cassandra-rackdc.properties
    container_name: database2
    command: --seeds=database,database2,database3
    networks:
      - network-database

  database3:
    depends_on:
      - database2
    image: scylladb/scylla:6.1
    restart: always
    ports:
    - 9044:9042
    expose:
      - 9042
    volumes:
      - db-data3:/var/lib/scylla
      - ./scylla/cassandra-rackdc.properties:/etc/scylla/cassandra-rackdc.properties
    container_name: database3
    command: --seeds=database,database2,database3
    networks:
      - network-database

  database-init:
    container_name: scylla-load-keyspace
    image: scylladb/scylla:6.1
    volumes:
      - ./scylla/scylladb.txt:/scylla_scripts/scylladb.txt
      - ./scylla/initdb.sh:/scylla_scripts/initdb.sh
    entrypoint: [ "sh", "/scylla_scripts/initdb.sh" ]
    networks:
      - network-database
volumes:
  db-data:
  db-data2:
  db-data3:

networks:
  network-database:
    driver: bridge